### PR TITLE
add invalid key value to stack trace

### PR DESCRIPTION
**Pull request by seanpreston**
This is a change to allow us to better debug invalid key failures. Something inside `fidectl generate dataset db` is creating an invalid key.

See: https://fidescommunity.slack.com/archives/C02UWB1BFC7/p1654884882219009

### CODE REVIEW

**Review by ThomasLaPiana — CHANGES_REQUESTED** [review]
Would like to see a test added that confirms this change works as intended

**Comment by ThomasLaPiana** [comment]
@seanpreston is this still a thing?

**Comment by seanpreston** [comment]
Thanks for the prod! Will add a test this week

**Comment by seanpreston** [comment]
> Would like to see a test added that confirms this change works as intended

`tests/fideslang/test_validation.py::test_invalid_chars_in_fides_key PASSED [ 46%]`

Hey @ThomasLaPiana this is ready for another look

**Review by ThomasLaPiana — APPROVED** [review]

**Comment by ThomasLaPiana** [comment]
should make our lives easier, thoughtful change! 💯

**Comment by ThomasLaPiana** [comment]
@seanpreston need to update the changelog and then you're good to merge!

**Pull request merged**
