### PR TITLE
Taxonomy Simplification for DataCategory and DataUse

### LINKED ISSUE #58: DataUse & DataCategory Simplifications
The following proposed changes to `fideslang` follow months of review and feedback from users. Most of these changes are due to confusion when implementing causing hesitation.

* Remove `identifiable`, `nonidentifiable`, `derived`, and `provided` subcategories
  * Remove the parent categories, combining the subcategories into one
* Rename `provide.system` to `provide.service`
* Move `account` to a subcategory of `user`
  * e.g. `user.account.email`, `user.contact.email`

### Describe the solution you'd like

Implementing these changes will provide some simplicity when selecting a `DataCategory` and help reduce the barrier to entry.

### Describe alternatives you've considered, if any

Maintaining the existing taxonomy as backwards compatible.

### Additional context

Some decision made around this change:
* Do not implement backwards compatibility for this breaking change
* Some suggested enhancements have been pushed to a later minor release of `fideslang`

### PR DESCRIPTION
**Pull request by SteveDMurphy**
Closes #58

### Code Changes

* [x] rename `provide.system` to `provide.service`
* [x] move account to a subcategory of `user`
* [x] remove `identifiable` and `non-identifiable` subcategories
* [x] remove `derived` and `provided` subcategories
* [x] remove all `account` categories
* [x] ~clean up `data_files/`~ These look really old if you [look back in time](https://github.com/ethyca/fideslang/tree/08f1d7c93edc5089a511d149568679545c40ade5), suggest updating or cleaning in a separate commit
* [x] update docs

### Steps to Confirm

* [x] The default taxonomy loads properly with no orphans
* [x] This branch can be installed to `fidesctl` with known adjustments as part of upgrading to `1.1.0`

### Pre-Merge Checklist

* [x] All CI Pipelines Succeeded
* [x] Documentation Updated
* [x] Issue Requirements are Met
* [x] Relevant Follow-Up Issues Created
* [x] Update `CHANGELOG.md`
* [x] Add `address` parent categories

### Description Of Changes

There are some unknown updates left to be made in regard to description, name, and potential further relationship management (`account` vs `contact`)

Much conversation happened on the issue to get us to this point. Adding a note to the issue in `fidesctl` as well to point to these docs as the single source of truth going forward

### CODE REVIEW

**Comment by SteveDMurphy** [comment]
@ThomasLaPiana I still have quite a few documentation updates in here, just to confirm we want to sort of duplicate the docs in here and in `fidesctl`, correct? Or are we okay pointing the `fidesctl` docs to these?

**Comment by SteveDMurphy** [comment]
Continuing to hold on docs changes until consensus reached in the issue, once we have that this should ship quickly along with the sibling issue in `fidesctl`

**Comment by ThomasLaPiana** [comment]
looks like the changes were finally agreed upon @SteveDMurphy , taking a look now :)

**Comment by SteveDMurphy** [comment]
Thanks @ThomasLaPiana !!! Just pushed them through and got the docs updates done as well. Re-validating in `fidesctl` now while awaiting a review

**Review by ThomasLaPiana — APPROVED** [review]
monstrous changes, but all LGTM!

**Comment by ThomasLaPiana** [comment]
@SteveDMurphy it would be cool to generate all of those docs from the source code...I'm sure there's a way to do that, I'm going to open a ticket for it

**Review by conceptualshark — APPROVED** [review]

**Pull request merged**
